{
 "title": "Number Counter",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Summary",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sentiment_summary_count", "legendFormat": "{{sentiment}}" }
   ]
  },
  {
   "title": "Histogram [positive] <-> [negative]",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "input_data_size_distribution_bucket{sentiment=\"positive\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "input_data_size_distribution_bucket{sentiment=\"negative\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Accuracy",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prediction_accuracy",
     "legendFormat": "Accuracy of sentiment predictions"
    }
   ]
  },
  {
   "title": "Counter",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "predictions_total",
     "legendFormat": "Total number of predictions made"
    },
    {
     "expr": "user_feedback_total",
     "legendFormat": "Total number of user feedback received"
    }
   ]
  }
 ]
}