services:
  frontend:
    image: ghcr.io/remla23-team11/app:latest
    ports:
      - 3000:3000
    environment:
      REACT_APP_API_URL: "http://localhost:8080"

  backend:
    image: ghcr.io/remla23-team11/model-service:latest
    ports:
      - 8080:8080
